exclude: ["local"]
url: http://juan.liu313.com
permalink: /:categories/:year/:title.html
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "no_intra_emphasis", "tables", "autolink", "strikethrough"]